apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vultisig-ingress
  namespace: verifier
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: verifier.vultisig.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: verifier
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dca-swap-ingress
  namespace: plugin-dca
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: dca-swap.vultisig.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server-swap
                port:
                  number: 8082
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dca-send-ingress
  namespace: plugin-dca
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: dca-send.vultisig.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server-send
                port:
                  number: 8083
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: grafana.vultisig.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
